#Logistic Regression

### Loading and Decribing data

In [1]:
import pandas as pd
data = pd.read_csv("Student-University.csv")
data.head(10)

X1         X2  y
0  34.623660  78.024693  0
1  30.286711  43.894998  0
2  35.847409  72.902198  0
3  60.182599  86.308552  1
4  79.032736  75.344376  1
5  45.083277  56.316372  0
6  61.106665  96.511426  1
7  75.024746  46.554014  1
8  76.098787  87.420570  1
9  84.432820  43.533393  1

In [2]:
data.describe()

X1          X2           y
count  100.000000  100.000000  100.000000
mean    65.644274   66.221998    0.600000
std     19.458222   18.582783    0.492366
min     30.058822   30.603263    0.000000
25%     50.919511   48.179205    0.000000
50%     67.032988   67.682381    1.000000
75%     80.212529   79.360605    1.000000
max     99.827858   98.869436    1.000000

## Splitting data

In [3]:
# Input data
x = data.iloc[:, [0,1] ].values

# Output data
y = data.iloc[:, 2].values

print(x[:5, :]) # Prinitng the first 5 rows of split input data
print()
print(y[:5])   # Printing the first 5 rows of split output data

[[34.62365962 78.02469282]
 [30.28671077 43.89499752]
 [35.84740877 72.90219803]
 [60.18259939 86.3085521 ]
 [79.03273605 75.34437644]]

[0 0 0 1 1]


## Data Preprocessing

In [4]:
from sklearn import preprocessing

# Normalising data
norX = preprocessing.scale(x)

# Printing first 5 rows of Normalised data
print(norX[:5, :])

[[-1.60224763  0.63834112]
 [-1.82625564 -1.2075414 ]
 [-1.53903969  0.3612943 ]
 [-0.28210129  1.0863683 ]
 [ 0.69152826  0.49337794]]


##Training and Testing

In [5]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

foldings = KFold(n_splits = 5)

for train_index, test_index in foldings.split(norX):
  xtrain, xtest, ytrain, ytest = train_test_split(norX, y, train_size=0.80, test_size=0.20, random_state=0)

  x1 = xtrain[:, 0]
  x2 = xtrain[:, 1]

  b0 = 0
  b1 = 0
  b2 = 0
  epoch = 10000
  alpha = 0.001

  while(epoch>0):
    for i in range(len(xtrain)):
      pred = b0 + b1*x1[i] + b2*x2[i]
      prediction = 1/(1 + np.exp(-pred))
      b0 = b0 + alpha*(ytrain[i]-prediction)*prediction*(1-prediction)*1.0
      b1 = b1 + alpha*(ytrain[i]-prediction)*prediction*(1-prediction)*x1[i]
      b2 = b2 + alpha*(ytrain[i]-prediction)*prediction*(1-prediction)*x2[i]
    epoch = epoch - 1

print(b0)
print(b1)
print(b2)


0.9875270298732238
2.669884877890649
2.7274062957733918


## Prediction

In [6]:
x3 = xtest[:, 0]
x4 = xtest[:, 1]
print(ytest)

pred_list = []
y_pred = [0]*len(xtest)

for i in range(len(xtest)):
  predo = b0 + b1*x3[i] + b2*x4[i]
  y_pred[i] = np.round(1/(1 + np.exp(-predo)))
  pred_list.append(int(y_pred[i]))

print(pred_list)

[1 0 0 0 1 1 1 1 0 1 0 0 0 1 1 1 0 1 1 1]
[0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1]


## Accuracy Score

In [7]:
from sklearn.metrics import accuracy_score
res = accuracy_score(ytest, y_pred)
acc = res*100
print("Accuracy in precentage:", acc, "%")

Accuracy in precentage: 80.0 %
